// Mock data for development (until database is connected)

import type { IProduct, ICategory, IUser, IBanner } from "./types/database"

export const mockCategories: ICategory[] = [
  {
    id: "1",
    name: "Electronics",
    slug: "electronics",
    description: "Latest gadgets and electronic devices",
    image_url: "/electronics-components.png",
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Fashion",
    slug: "fashion",
    description: "Trendy clothing and accessories",
    image_url: "/diverse-fashion-collection.png",
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Home & Garden",
    slug: "home-garden",
    description: "Everything for your home",
    image_url: "/cozy-living-room.png",
    display_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Gear for active lifestyles",
    image_url: "/assorted-sports-gear.png",
    display_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockProducts: IProduct[] = [
  {
    id: "1",
    name: "Wireless Noise-Cancelling Headphones",
    slug: "wireless-noise-cancelling-headphones",
    description:
      "Premium wireless headphones with active noise cancellation, 30-hour battery life, and superior sound quality. Perfect for travel, work, or relaxation.",
    short_description: "Premium wireless headphones with ANC",
    category_id: "1",
    price: 299.99,
    compare_at_price: 399.99,
    sku: "WH-1000XM5",
    track_inventory: true,
    stock_quantity: 45,
    low_stock_threshold: 10,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "1",
        product_id: "1",
        image_url: "/wireless-headphones.png",
        alt_text: "Wireless Headphones",
        display_order: 0,
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
    average_rating: 4.8,
    review_count: 234,
  },
  {
    id: "2",
    name: "Smart Watch Pro",
    slug: "smart-watch-pro",
    description:
      "Advanced fitness tracking, heart rate monitoring, GPS, and smartphone notifications. Water-resistant up to 50m.",
    short_description: "Advanced fitness smartwatch",
    category_id: "1",
    price: 399.99,
    compare_at_price: 499.99,
    sku: "SW-PRO-2024",
    track_inventory: true,
    stock_quantity: 67,
    low_stock_threshold: 10,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "2",
        product_id: "2",
        image_url: "/modern-smartwatch.png",
        alt_text: "Smart Watch",
        display_order: 0,
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
    average_rating: 4.6,
    review_count: 189,
  },
  {
    id: "3",
    name: "Premium Leather Jacket",
    slug: "premium-leather-jacket",
    description:
      "Genuine leather jacket with classic design. Features multiple pockets, comfortable lining, and durable construction.",
    short_description: "Genuine leather jacket",
    category_id: "2",
    price: 249.99,
    sku: "LJ-CLASSIC-BLK",
    track_inventory: true,
    stock_quantity: 23,
    low_stock_threshold: 10,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "3",
        product_id: "3",
        image_url: "/classic-leather-jacket.png",
        alt_text: "Leather Jacket",
        display_order: 0,
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
    average_rating: 4.7,
    review_count: 92,
  },
  {
    id: "4",
    name: "Designer Sunglasses",
    slug: "designer-sunglasses",
    description: "UV400 protection, polarized lenses, and stylish frame design. Comes with protective case.",
    short_description: "Polarized designer sunglasses",
    category_id: "2",
    price: 159.99,
    compare_at_price: 229.99,
    sku: "SG-POLAR-001",
    track_inventory: true,
    stock_quantity: 89,
    low_stock_threshold: 10,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "4",
        product_id: "4",
        image_url: "/stylish-sunglasses.png",
        alt_text: "Designer Sunglasses",
        display_order: 0,
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
    average_rating: 4.5,
    review_count: 67,
  },
  {
    id: "5",
    name: "Modern Coffee Table",
    slug: "modern-coffee-table",
    description:
      "Sleek minimalist design with tempered glass top and solid wood legs. Perfect for contemporary living spaces.",
    short_description: "Minimalist glass coffee table",
    category_id: "3",
    price: 349.99,
    sku: "CT-MOD-001",
    track_inventory: true,
    stock_quantity: 15,
    low_stock_threshold: 5,
    is_featured: true,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "5",
        product_id: "5",
        image_url: "/modern-coffee-table.png",
        alt_text: "Coffee Table",
        display_order: 0,
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
    average_rating: 4.9,
    review_count: 45,
  },
  {
    id: "6",
    name: "Yoga Mat Premium",
    slug: "yoga-mat-premium",
    description:
      "Extra thick, non-slip yoga mat with carrying strap. Eco-friendly materials, perfect for all types of yoga and exercise.",
    short_description: "Non-slip premium yoga mat",
    category_id: "4",
    price: 49.99,
    sku: "YM-PREM-001",
    track_inventory: true,
    stock_quantity: 156,
    low_stock_threshold: 20,
    is_featured: false,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      {
        id: "6",
        product_id: "6",
        image_url: "/rolled-yoga-mat.png",
        alt_text: "Yoga Mat",
        display_order: 0,
        is_primary: true,
        created_at: new Date().toISOString(),
      },
    ],
    average_rating: 4.7,
    review_count: 312,
  },
]

export const mockBanners: IBanner[] = [
  {
    id: "1",
    title: "Summer Sale - Up to 50% Off",
    //image_url: "/summer-sale-banner.png",
    image_url: "/e_com_banner.jpg",
    link_url: "/products?sale=true",
    description: "Limited time offer on selected items",
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "New Arrivals",
    //image_url: "/new-products-banner.png",
    image_url: "/e_com_banner.jpg",
    link_url: "/products?sort=newest",
    description: "Check out our latest products",
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockUser: IUser = {
  id: "user-1",
  email: "demo@example.com",
  full_name: "Demo User",
  phone: "+1234567890",
  role: "customer",
  email_verified: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const mockAdminUser: IUser = {
  id: "admin-1",
  email: "admin@example.com",
  full_name: "Admin User",
  role: "admin",
  email_verified: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}
